# This is a basic workflow to help you get started with Actions
#
# 1
name: CIA

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: bash sh.sh
        env:
          KEY: ${{secrets.SS}}
      - run: echo $KEY>>time.txt
      - uses: actions/checkout@v2
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.txt
          git commit -m "update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Commit files
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add time.txt
#          git commit -m "Robot"
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          branch: ${{ github.ref }}
#          repository: 'xxooxxooxx/tset2'
#          github_token: ${{ secrets.SS }}
